version: "3.9"

services:
  web:
    build: .
    restart: always
    command: poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
